---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/NucBeforeWatershed/mod3mergedsubfigreplacedfig-NucWatershed.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/90123/articles/208220/master/folder/figures/NucBeforeWatershed"
    url: "/users/90123/articles/208220/master/file/figures/NucBeforeWatershed/mod3mergedsubfigreplacedfig-NucWatershed.svg"
