language: python

python:
  - "2.7"

# safelist
branches:
  only:
    - struct_authorea

before_install:
  - bash ./preinstall.sh

install:
  - pip install gitpython

script: 
  - python latex_update_codeGIT.py

after_success:
  - bash ./githubpush.sh

