---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Ch3BeforeLaplacian/mod3mergedsubfigreplacedfig-LogFilter.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/90123/articles/208220/master/folder/figures/Ch3BeforeLaplacian"
    url: "/users/90123/articles/208220/master/file/figures/Ch3BeforeLaplacian/mod3mergedsubfigreplacedfig-LogFilter.svg"
